###########################
# Configuration for rubocop
# in .rubocop.yml
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.
AllCops:
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/DoubleNegation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Naming/VariableNumber:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

LineLength:
  Max: 119 # github diff (ex. +-)

Documentation:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Exclude:
    - "**/spec/**/*"

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - "**/spec/**/*"

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/RedundantCondition: # Double pipes(||) on multiline is not so clear.
  Enabled: false
