language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
cache: bundler
before_script: wget -O ~/.rubocop.yml https://quickpay.github.io/development/.rubocop.yml
script: bundle exec rake
notifications:
  slack:
    secure: SixeTgiVsOaeWyKwICxLJ0GLN/C9j6qW1ZdaEytIDuZaBAn9oArrRGkJiehFdlzcPUHwzMWC0vl9GQzyBhZ7dbq+B53QY1mH9LTb9A53Y2d1OO1kBjJAkC5Yprvpjm52+x889Dwlz0bfLETvLsC2ej0NZDvSSLKFjpZZIZMOWkg=
